/**
 * 🇮🇳 BHARAT SAFE YATRA — SAFETY & EMERGENCY SERVICE (Client-side)
 * Calls: GET /api/v1/safety/contacts, GET /api/v1/safety/advisories,
 *        GET /api/v1/safety/nearby, POST /api/v1/safety/sos
 *
 * CRITICAL: Emergency contacts (112, 108, 1363) are DETERMINISTIC.
 * They are not generated by AI and cannot be overridden at runtime.
 */

import type { ApiResponse, EmergencyFacility, EmergencyNationalContact, ActiveTravelAdvisory, SOSRequest, SOSResponse } from '../types';

const BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? '/api/v1';

export const safetyService = {
  async getNationalContacts(): Promise<ApiResponse<EmergencyNationalContact[]>> {
    const res = await fetch(`${BASE}/safety/contacts`, { next: { revalidate: 86400 } }); // 24h cache — numbers don't change daily
    if (!res.ok) return { success: false, data: [], error: { code: 'FETCH_ERROR', message: 'Failed to load emergency contacts' } };
    return res.json() as Promise<ApiResponse<EmergencyNationalContact[]>>;
  },

  async getActiveAdvisories(territory?: string): Promise<ApiResponse<ActiveTravelAdvisory[]>> {
    const params = territory ? `?territory=${encodeURIComponent(territory)}` : '';
    const res = await fetch(`${BASE}/safety/advisories${params}`, { next: { revalidate: 300 } }); // 5min cache
    if (!res.ok) return { success: false, data: [], error: { code: 'FETCH_ERROR', message: 'Failed to load advisories' } };
    return res.json() as Promise<ApiResponse<ActiveTravelAdvisory[]>>;
  },

  async getEmergencyFacilities(lat?: number, lng?: number, radius?: number): Promise<ApiResponse<EmergencyFacility[]>> {
    let url = `${BASE}/safety/nearby`;
    if (lat !== undefined && lng !== undefined) {
      url += `?lat=${lat}&lng=${lng}&radius=${radius ?? 50}`;
    }
    const res = await fetch(url, { cache: 'no-store' }); // Real-time — no cache
    if (!res.ok) return { success: false, data: [], error: { code: 'FETCH_ERROR', message: 'Failed to find nearby facilities' } };
    return res.json() as Promise<ApiResponse<EmergencyFacility[]>>;
  },

  async triggerSOS(req: SOSRequest): Promise<ApiResponse<SOSResponse>> {
    const res = await fetch(`${BASE}/safety/sos`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        latitude: req.latitude,
        longitude: req.longitude,
        accuracyMeters: req.accuracyMeters,
        itineraryId: req.itineraryId,
      }),
      cache: 'no-store',
    });
    if (!res.ok) {
      return {
        success: false,
        data: null as unknown as SOSResponse,
        error: { code: 'SOS_ERROR', message: 'SOS processing failed. DIAL 112 IMMEDIATELY.' },
      };
    }
    return res.json() as Promise<ApiResponse<SOSResponse>>;
  },
};
